# Generated by Django 3.0.7 on 2020-06-19 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200618_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tesouro_direto_compra',
            name='valor',
            field=models.PositiveIntegerField(),
        ),
    ]
