# Generated by Django 3.0.7 on 2020-06-22 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200622_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='tesouro_direto_compra',
            name='id_compra',
            field=models.PositiveIntegerField(default='123456'),
        ),
    ]
