# Generated by Django 3.0.7 on 2020-06-23 14:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_tesouro_direto_compra_id_compra'),
    ]

    operations = [
        migrations.AddField(
            model_name='tesouro_direto_compra',
            name='dia_da_compra',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
