# Generated by Django 3.0.7 on 2020-06-23 23:47

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0007_tesouro_direto_compra_dia_da_compra'),
    ]

    operations = [
        migrations.CreateModel(
            name='Novo_Fundo_Investimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('preco_unidade', models.PositiveIntegerField()),
                ('classe', models.CharField(max_length=255)),
                ('prazo', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Fundo_Investimento_Compra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.PositiveIntegerField()),
                ('id_compra', models.PositiveIntegerField(default='123456')),
                ('dia_da_compra', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('comprador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('produto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Novo_Fundo_Investimento')),
            ],
        ),
    ]
