# Generated by Django 3.0.7 on 2020-06-23 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_fundo_investimento_compra_novo_fundo_investimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novo_fundo_investimento',
            name='classe',
            field=models.CharField(choices=[('Ação', 'Ação'), ('Cambial', 'Cambial'), ('Multimercado', 'Multimercado'), ('Renda Fixa', 'Renda Fixa')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='novo_tesouro_direto',
            name='indexador',
            field=models.CharField(choices=[('IPCA', 'IPCA'), ('SELIC', 'SELIC'), ('Prefixado', 'Prefixado')], max_length=255, null=True),
        ),
    ]
