# Generated by Django 3.0.7 on 2020-06-23 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20200623_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novo_fundo_investimento',
            name='prazo',
            field=models.CharField(choices=[('D+1', 'D+1'), ('D+4', 'D+4'), ('D+30', 'D+30'), ('D+60', 'D+60')], max_length=255, null=True),
        ),
    ]
