# Generated by Django 3.0.7 on 2020-06-24 00:34

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0010_auto_20200623_2359'),
    ]

    operations = [
        migrations.CreateModel(
            name='Novo_Renda_Fixa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('vencimento', models.PositiveIntegerField()),
                ('classe', models.CharField(choices=[('CDB', 'CDB'), ('LCA', 'LCA'), ('LCI', 'LCI'), ('LF', 'LF'), ('LC', 'LC')], max_length=255, null=True)),
                ('horario_limite', models.CharField(max_length=255)),
                ('preco_unidade', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Renda_Fixa_Compra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.PositiveIntegerField()),
                ('id_compra', models.PositiveIntegerField(default='123456')),
                ('dia_da_compra', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('comprador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('produto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Novo_Renda_Fixa')),
            ],
        ),
    ]
